version: '3'

vars:
    GOLANGCI_LINT_VERSION: 'v2.13.1'
    BIN_DIR: '{{.ROOT_DIR}}/bin'
    BIN_EXT: '{{if eq OS "windows"}}.exe{{end}}' # shit for windows
    GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint{{.BIN_EXT}}'

includes:
    scraper: ./services/scraper
    tg-bot: ./services/tg-bot
    config: ./libs/config
    proto: ./proto

tasks:
    run:
        desc: Поднимает весь стек (docker compose up --build)
        cmd: docker compose --env-file=./configs/.env up --build -d

    down:
        desc: Останавливает стек и удаляет volumes
        cmd: docker compose --env-file=./configs/.env down -v

    deps:tidy:
        desc: go mod tidy во всех модулях
        cmds:
            - go -C services/scraper mod tidy
            - go -C services/tg-bot mod tidy
            - go -C libs/config mod tidy
            - go -C proto mod tidy

    test:
        desc: Unit-тесты всех модулей
        cmds:
            - task: scraper:test
            - task: tg-bot:test
            - task: config:test
            - task: proto:test

    test-integration:
        desc: Интеграционные тесты сервисов (нужен запущенный Docker)
        cmds:
            - task: scraper:test:integration
            - task: tg-bot:test:integration

    format:
        desc: Форматирует все модули
        deps:
            - scraper:format
            - tg-bot:format
            - config:format
            - proto:format

    lint:
        desc: Линтим все модули (последовательно — golangci-lint не любит параллельный запуск)
        cmds:
            - task: scraper:lint
            - task: tg-bot:lint
            - task: config:lint
            - task: proto:lint

    lint:fix:
        desc: Фиксит golangci-lint во всех модулях
        cmds:
            - task: scraper:lint:fix
            - task: tg-bot:lint:fix
            - task: config:lint:fix
            - task: proto:lint:fix

    install-golangci-lint:
        desc: Устанавливает golangci-lint в каталог bin
        status:
            - test -f {{.GOLANGCI_LINT}}
        cmds:
            - |
                echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
                GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
