// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: scraper.proto

// Генерация: из корня репозитория — `task proto:gen`
// (вручную: buf + protoc-gen-go + protoc-gen-go-grpc в PATH,
// затем `buf generate` из каталога proto/).

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduleService_GetGroupSchedule_FullMethodName         = "/scraper.ScheduleService/GetGroupSchedule"
	ScheduleService_GetGroupScheduleByWeek_FullMethodName   = "/scraper.ScheduleService/GetGroupScheduleByWeek"
	ScheduleService_GetAvailableWeeks_FullMethodName        = "/scraper.ScheduleService/GetAvailableWeeks"
	ScheduleService_GetTeacherSchedule_FullMethodName       = "/scraper.ScheduleService/GetTeacherSchedule"
	ScheduleService_GetTeacherScheduleByWeek_FullMethodName = "/scraper.ScheduleService/GetTeacherScheduleByWeek"
	ScheduleService_GetAvailableTeacherWeeks_FullMethodName = "/scraper.ScheduleService/GetAvailableTeacherWeeks"
	ScheduleService_GetTeacherNames_FullMethodName          = "/scraper.ScheduleService/GetTeacherNames"
)

// ScheduleServiceClient is the client API for ScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleServiceClient interface {
	GetGroupSchedule(ctx context.Context, in *GroupScheduleRequest, opts ...grpc.CallOption) (*GroupScheduleResponse, error)
	GetGroupScheduleByWeek(ctx context.Context, in *GroupScheduleRequest, opts ...grpc.CallOption) (*GroupScheduleResponse, error)
	GetAvailableWeeks(ctx context.Context, in *AvailableWeeksRequest, opts ...grpc.CallOption) (*AvailableWeeksResponse, error)
	GetTeacherSchedule(ctx context.Context, in *TeacherScheduleRequest, opts ...grpc.CallOption) (*TeacherScheduleResponse, error)
	GetTeacherScheduleByWeek(ctx context.Context, in *TeacherScheduleRequest, opts ...grpc.CallOption) (*TeacherScheduleResponse, error)
	GetAvailableTeacherWeeks(ctx context.Context, in *AvailableWeeksRequest, opts ...grpc.CallOption) (*AvailableWeeksResponse, error)
	GetTeacherNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TeacherNamesResponse, error)
}

type scheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleServiceClient(cc grpc.ClientConnInterface) ScheduleServiceClient {
	return &scheduleServiceClient{cc}
}

func (c *scheduleServiceClient) GetGroupSchedule(ctx context.Context, in *GroupScheduleRequest, opts ...grpc.CallOption) (*GroupScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetGroupSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetGroupScheduleByWeek(ctx context.Context, in *GroupScheduleRequest, opts ...grpc.CallOption) (*GroupScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetGroupScheduleByWeek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetAvailableWeeks(ctx context.Context, in *AvailableWeeksRequest, opts ...grpc.CallOption) (*AvailableWeeksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailableWeeksResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetAvailableWeeks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetTeacherSchedule(ctx context.Context, in *TeacherScheduleRequest, opts ...grpc.CallOption) (*TeacherScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetTeacherSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetTeacherScheduleByWeek(ctx context.Context, in *TeacherScheduleRequest, opts ...grpc.CallOption) (*TeacherScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherScheduleResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetTeacherScheduleByWeek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetAvailableTeacherWeeks(ctx context.Context, in *AvailableWeeksRequest, opts ...grpc.CallOption) (*AvailableWeeksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailableWeeksResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetAvailableTeacherWeeks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleServiceClient) GetTeacherNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TeacherNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherNamesResponse)
	err := c.cc.Invoke(ctx, ScheduleService_GetTeacherNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleServiceServer is the server API for ScheduleService service.
// All implementations must embed UnimplementedScheduleServiceServer
// for forward compatibility.
type ScheduleServiceServer interface {
	GetGroupSchedule(context.Context, *GroupScheduleRequest) (*GroupScheduleResponse, error)
	GetGroupScheduleByWeek(context.Context, *GroupScheduleRequest) (*GroupScheduleResponse, error)
	GetAvailableWeeks(context.Context, *AvailableWeeksRequest) (*AvailableWeeksResponse, error)
	GetTeacherSchedule(context.Context, *TeacherScheduleRequest) (*TeacherScheduleResponse, error)
	GetTeacherScheduleByWeek(context.Context, *TeacherScheduleRequest) (*TeacherScheduleResponse, error)
	GetAvailableTeacherWeeks(context.Context, *AvailableWeeksRequest) (*AvailableWeeksResponse, error)
	GetTeacherNames(context.Context, *Empty) (*TeacherNamesResponse, error)
	mustEmbedUnimplementedScheduleServiceServer()
}

// UnimplementedScheduleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduleServiceServer struct{}

func (UnimplementedScheduleServiceServer) GetGroupSchedule(context.Context, *GroupScheduleRequest) (*GroupScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) GetGroupScheduleByWeek(context.Context, *GroupScheduleRequest) (*GroupScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupScheduleByWeek not implemented")
}
func (UnimplementedScheduleServiceServer) GetAvailableWeeks(context.Context, *AvailableWeeksRequest) (*AvailableWeeksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableWeeks not implemented")
}
func (UnimplementedScheduleServiceServer) GetTeacherSchedule(context.Context, *TeacherScheduleRequest) (*TeacherScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherSchedule not implemented")
}
func (UnimplementedScheduleServiceServer) GetTeacherScheduleByWeek(context.Context, *TeacherScheduleRequest) (*TeacherScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherScheduleByWeek not implemented")
}
func (UnimplementedScheduleServiceServer) GetAvailableTeacherWeeks(context.Context, *AvailableWeeksRequest) (*AvailableWeeksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableTeacherWeeks not implemented")
}
func (UnimplementedScheduleServiceServer) GetTeacherNames(context.Context, *Empty) (*TeacherNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherNames not implemented")
}
func (UnimplementedScheduleServiceServer) mustEmbedUnimplementedScheduleServiceServer() {}
func (UnimplementedScheduleServiceServer) testEmbeddedByValue()                         {}

// UnsafeScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleServiceServer will
// result in compilation errors.
type UnsafeScheduleServiceServer interface {
	mustEmbedUnimplementedScheduleServiceServer()
}

func RegisterScheduleServiceServer(s grpc.ServiceRegistrar, srv ScheduleServiceServer) {
	// If the following call panics, it indicates UnimplementedScheduleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduleService_ServiceDesc, srv)
}

func _ScheduleService_GetGroupSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetGroupSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetGroupSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetGroupSchedule(ctx, req.(*GroupScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetGroupScheduleByWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetGroupScheduleByWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetGroupScheduleByWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetGroupScheduleByWeek(ctx, req.(*GroupScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetAvailableWeeks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableWeeksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetAvailableWeeks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetAvailableWeeks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetAvailableWeeks(ctx, req.(*AvailableWeeksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetTeacherSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetTeacherSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetTeacherSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetTeacherSchedule(ctx, req.(*TeacherScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetTeacherScheduleByWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetTeacherScheduleByWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetTeacherScheduleByWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetTeacherScheduleByWeek(ctx, req.(*TeacherScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetAvailableTeacherWeeks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableWeeksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetAvailableTeacherWeeks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetAvailableTeacherWeeks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetAvailableTeacherWeeks(ctx, req.(*AvailableWeeksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleService_GetTeacherNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleServiceServer).GetTeacherNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduleService_GetTeacherNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleServiceServer).GetTeacherNames(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleService_ServiceDesc is the grpc.ServiceDesc for ScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.ScheduleService",
	HandlerType: (*ScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroupSchedule",
			Handler:    _ScheduleService_GetGroupSchedule_Handler,
		},
		{
			MethodName: "GetGroupScheduleByWeek",
			Handler:    _ScheduleService_GetGroupScheduleByWeek_Handler,
		},
		{
			MethodName: "GetAvailableWeeks",
			Handler:    _ScheduleService_GetAvailableWeeks_Handler,
		},
		{
			MethodName: "GetTeacherSchedule",
			Handler:    _ScheduleService_GetTeacherSchedule_Handler,
		},
		{
			MethodName: "GetTeacherScheduleByWeek",
			Handler:    _ScheduleService_GetTeacherScheduleByWeek_Handler,
		},
		{
			MethodName: "GetAvailableTeacherWeeks",
			Handler:    _ScheduleService_GetAvailableTeacherWeeks_Handler,
		},
		{
			MethodName: "GetTeacherNames",
			Handler:    _ScheduleService_GetTeacherNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraper.proto",
}
