// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: scraper.proto

package scraperpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllSchedulesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Groups        []*GroupScheduleResponse `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllSchedulesResponse) Reset() {
	*x = AllSchedulesResponse{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSchedulesResponse) ProtoMessage() {}

func (x *AllSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSchedulesResponse.ProtoReflect.Descriptor instead.
func (*AllSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *AllSchedulesResponse) GetGroups() []*GroupScheduleResponse {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupNum      int32                  `protobuf:"varint,1,opt,name=groupNum,proto3" json:"groupNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupScheduleRequest) Reset() {
	*x = GroupScheduleRequest{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupScheduleRequest) ProtoMessage() {}

func (x *GroupScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupScheduleRequest.ProtoReflect.Descriptor instead.
func (*GroupScheduleRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *GroupScheduleRequest) GetGroupNum() int32 {
	if x != nil {
		return x.GroupNum
	}
	return 0
}

type GroupScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Week          string                 `protobuf:"bytes,1,opt,name=week,proto3" json:"week,omitempty"`
	Day           []*Day                 `protobuf:"bytes,2,rep,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupScheduleResponse) Reset() {
	*x = GroupScheduleResponse{}
	mi := &file_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupScheduleResponse) ProtoMessage() {}

func (x *GroupScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupScheduleResponse.ProtoReflect.Descriptor instead.
func (*GroupScheduleResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *GroupScheduleResponse) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GroupScheduleResponse) GetDay() []*Day {
	if x != nil {
		return x.Day
	}
	return nil
}

type Day struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject       []*Subject             `protobuf:"bytes,2,rep,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Day) Reset() {
	*x = Day{}
	mi := &file_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Day) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Day) ProtoMessage() {}

func (x *Day) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Day.ProtoReflect.Descriptor instead.
func (*Day) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *Day) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Day) GetSubject() []*Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Empty         bool                   `protobuf:"varint,3,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *Subject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subject) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Subject) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\ascraper\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x14AllSchedulesResponse\x126\n" +
	"\x06groups\x18\x01 \x03(\v2\x1e.scraper.GroupScheduleResponseR\x06groups\"2\n" +
	"\x14GroupScheduleRequest\x12\x1a\n" +
	"\bgroupNum\x18\x01 \x01(\x05R\bgroupNum\"K\n" +
	"\x15GroupScheduleResponse\x12\x12\n" +
	"\x04week\x18\x01 \x01(\tR\x04week\x12\x1e\n" +
	"\x03day\x18\x02 \x03(\v2\f.scraper.DayR\x03day\"E\n" +
	"\x03Day\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\asubject\x18\x02 \x03(\v2\x10.scraper.SubjectR\asubject\"I\n" +
	"\aSubject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x14\n" +
	"\x05empty\x18\x03 \x01(\bR\x05empty2\xae\x01\n" +
	"\x0fScheduleService\x12Q\n" +
	"\x10GetGroupSchedule\x12\x1d.scraper.GroupScheduleRequest\x1a\x1e.scraper.GroupScheduleResponse\x12H\n" +
	"\x0fGetAllSchedules\x12\x16.google.protobuf.Empty\x1a\x1d.scraper.AllSchedulesResponseB?Z=github.com/arseniizyk/mgkct-schedule-bot/libs/proto;scraperpbb\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scraper_proto_goTypes = []any{
	(*AllSchedulesResponse)(nil),  // 0: scraper.AllSchedulesResponse
	(*GroupScheduleRequest)(nil),  // 1: scraper.GroupScheduleRequest
	(*GroupScheduleResponse)(nil), // 2: scraper.GroupScheduleResponse
	(*Day)(nil),                   // 3: scraper.Day
	(*Subject)(nil),               // 4: scraper.Subject
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_scraper_proto_depIdxs = []int32{
	2, // 0: scraper.AllSchedulesResponse.groups:type_name -> scraper.GroupScheduleResponse
	3, // 1: scraper.GroupScheduleResponse.day:type_name -> scraper.Day
	4, // 2: scraper.Day.subject:type_name -> scraper.Subject
	1, // 3: scraper.ScheduleService.GetGroupSchedule:input_type -> scraper.GroupScheduleRequest
	5, // 4: scraper.ScheduleService.GetAllSchedules:input_type -> google.protobuf.Empty
	2, // 5: scraper.ScheduleService.GetGroupSchedule:output_type -> scraper.GroupScheduleResponse
	0, // 6: scraper.ScheduleService.GetAllSchedules:output_type -> scraper.AllSchedulesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
