version: '3'

vars:
  BIN_EXT: '{{if eq OS "windows"}}.exe{{end}}' # shit for windows

tasks:
  tidy:
    desc: go mod tidy
    cmds:
      - go mod tidy

  test:
    desc: Unit-тесты tg-bot
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go test ./...

  test:integration:
    desc: Интеграционные тесты tg-bot (нужен запущенный Docker)
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go test -tags=integration ./...

  format:
    desc: Форматирует server (gofumpt + gci)
    dir: '{{.TASKFILE_DIR}}'
    deps: [":install-formatters"]
    cmds:
      - '"{{.ROOT_DIR}}/bin/gofumpt{{.BIN_EXT}}" -extra -w .'
      - '"{{.ROOT_DIR}}/bin/gci{{.BIN_EXT}}" write -s standard -s default -s "prefix(github.com/arseniizyk/mgkct-schedule-bot/services/tg-bot)" .'

  lint:
    desc: Линтим tg-bot
    dir: '{{.TASKFILE_DIR}}'
    deps: [':install-golangci-lint']
    cmds:
      - '"{{.ROOT_DIR}}/bin/golangci-lint{{.BIN_EXT}}" run ./... --config={{.ROOT_DIR}}/.golangci.yml'

  lint:fix:
    desc: Фиксит golangci-lint в tg-bot
    dir: '{{.TASKFILE_DIR}}'
    deps: [':install-golangci-lint']
    cmds:
      - '"{{.ROOT_DIR}}/bin/golangci-lint{{.BIN_EXT}}" run ./... --fix --config={{.ROOT_DIR}}/.golangci.yml'
