# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
    push:
        branches: '**'
    pull_request:
        branches: '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.25'

            - name: Scraper dependencies
              working-directory: ./services/scraper
              run: go mod download

            - name: Build scraper
              working-directory: ./services/scraper
              run: go build -v ./cmd/main.go

            - name: Tg-bot dependencies
              working-directory: ./services/tg-bot
              run: go mod download

            - name: Build tg-bot
              working-directory: ./services/tg-bot
              run: go build -v ./cmd/main.go

    golangci-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.25

            - name: Golangci-lint scraper
              uses: golangci/golangci-lint-action@v8.0.0
              with:
                  working-directory: ./services/scraper

            - name: Golangci-lint tg-bot
              uses: golangci/golangci-lint-action@v8.0.0
              with:
                  working-directory: ./services/tg-bot

            # - name: Test
            #   run: go test -v ./...
